### ISSUE TITLE
Launch mechanism broken

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/desktop-integration#1]
After building an example AppImage of Firefox (which is, due to the structure of the AppImages repository, only possible after pushing the change to GitHub, since the files are downloaded during the builds), I noticed that the new dialog doesn't actually attempt to run the AppImage it is contained in.

@darealshinji has built a nice UI, no question, it's fast, and works fine, but it lacks quite some functionality.

We should port this as soon as possible to allow this to work as intended.

**Comment by darealshinji** [comment]
Try to run the app with `system("./bin/firefox &")`, that worked on my mkvtoolnix AppImage.

**Comment by probonopd** [comment]
Thanks for testing @TheAssassin. Let's not bring this into the AppImages repository until we know for sure that everything is working as intended. It is possible to run `pkg2appimage` on a local machine to test.

**Comment by TheAssassin** [comment]
I fixed this, and it works now. I'm on integrating libappimage into the application to make use of the desktop integration in it. That's a great way of reusing libappimage.
