### ISSUE TITLE
Has many dependencies, including SSL

### ISSUE THREAD

**Issue by probonopd** [AppImage/desktop-integration#4]
As of 668dd7e, the build artefacts have many dependencies, many of which cannot reasonably be expected to be part of each target system, and frankly should not be needed for a desktop integration dialog at all (e.g. SSL and Crypto stuff but also some of the libg* stuff).

```
me@host:~$ ldd Downloads/dialog-x86_64 
	linux-vdso.so.1 =>  (0x00007ffc264f5000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f05cbac0000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f05cb8a3000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f05cb568000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f05cb35e000)
	libXft.so.2 => /usr/lib/x86_64-linux-gnu/libXft.so.2 (0x00007f05cb149000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f05caf05000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f05caceb000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f05caac6000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f05ca7b4000)
	libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f05ca42c000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f05ca1d9000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f05c9fd4000)
	libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007f05c9dd2000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f05c9bca000)
	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f05c98b5000)
	libssl.so.10 => not found
	libcrypto.so.10 => not found
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f05c9532000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f05c9229000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f05c9013000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f05c8c49000)
	/lib64/ld-linux-x86-64.so.2 (0x000055ff75bb2000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f05c8a27000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f05c877d000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f05c8553000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f05c82e3000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f05c80c0000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f05c7ea5000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f05c7c9d000)
	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f05c79f4000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f05c77f0000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f05c75e6000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f05c73d3000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f05c71cf000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f05c6fc8000)
  ```

If this cannot easily be resolved within a short timeframe, I'd ask to revert https://github.com/AppImage/AppImages/commit/e06c37c47a86f955fd15d127463f518c726ea61c in the meantime, since currently this breaks all AppImages produced in the https://github.com/AppImage/AppImages project.

**Comment by TheAssassin** [comment]
Strange. On my local system, the dependency to `libssl` isn't there, although it's defined in the CMake configuration.

The only parts libssl is being required for is some hashing stuff for the verification. So, one way to get rid of it is to use some other implementation for these. We don't need a full blown crypto library, but we shouldn't write these ourselves (rule no. 1 when talking about crypto code). We can probably find some header containing a full and verified(!) implementation on the internet.

We can get rid of a few other libraries, such as libcairo, which we don't use since we load pictures as PNGs. I am pretty confident that FLTK's CMake configuration has a switch for that. Also, FLTK can be configured to link such stuff statically, so in case there is no such switch, we can opt for that instead.

If you have problems with other dependencies, please list them here. But I personally consider only libssl  and its dependencies problematic.

By the way, you should re-run it with `lddtree` to see which of the dependencies are just pulled in by others, to see which top level dependencies we should focus on.

It might also be worth comparing the `ldd` list to our exclude list.

**Comment by probonopd** [comment]
> The only parts libssl is being required for is some hashing stuff for the verification.

The immediate issue at hand here is that _desktop integration_ is not doing any hashing stuff for the verification at all, yet still has this dependency...

> So, one way to get rid of it is to use some other implementation for these. We don't need a full blown crypto library, but we shouldn't write these ourselves (rule no. 1 when talking about crypto code). We can probably find some header containing a full and verified(!) implementation on the internet.

True. But I think that's a separate issue.

**Comment by probonopd** [comment]
> By the way, you should re-run it with lddtree to see which of the dependencies are just pulled in by others, to see which top level dependencies we should focus on.

```
me@host:~$ lddtree Downloads/dialog-x86_64 
dialog-x86_64 => Downloads/dialog-x86_64 (interpreter => /lib64/ld-linux-x86-64.so.2)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2
        ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
    libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1
            libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6
            libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6
    libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1
    libXft.so.2 => /usr/lib/x86_64-linux-gnu/libXft.so.2
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6
    libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1
    libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0
    libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3
    libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2
    libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6
    libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0
    libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1
    libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2
        libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0
        libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0
        libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6
    libssl.so.10 => not found
    libcrypto.so.10 => not found
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
```

> If you have problems with other dependencies, please list them here. 

It may _only_ depend on libraries that are on the excludelist. Because otherwise it introduces additional dependencies into the AppImage.

**Comment by TheAssassin** [comment]
@probonopd I can't build `n` versions of libappimage for `n` different projects. Other applications might not want to link to libssl as well, so replacing it seems like the best solution for this issue.

But, as noted in https://github.com/AppImage/AppImageKit/pull/610, it doesn't even seem to be required.

**Comment by probonopd** [comment]
Hence I am not a fan of `libappimage` going _into_ any AppImages other than the ones containing tools to make AppImages... and if we use `libappimage`, can't we link the parts that are needed statically?

**Comment by TheAssassin** [comment]
So what do you suggest? Duplicate code in all places? That's really an antipattern.

**Comment by probonopd** [comment]
Let's revert https://github.com/AppImage/AppImages/commit/e06c37c47a86f955fd15d127463f518c726ea61c until we have had time to find a solution and discuss.

**Comment by TheAssassin** [comment]
The solution has just been pushed.

**Comment by probonopd** [comment]
Cool, thanks. Lemme test.

**Comment by TheAssassin** [comment]
Give it some time to build, please.
